DHIS2_BASE_URL: https://play.im.dhis2.org/stable-2-42-3-1
DHIS2_USERNAME: admin
DHIS2_PASSWORD: district

DHIS2_DATA_ELEMENT_ID: urBVcn8nZ7V
DHIS2_TIMEZONE_OFFSET: 0
DHIS2_DRY_RUN: True

IMPORT_VARIABLE: 2m_temperature
IMPORT_VALUE_COL: t2m
IMPORT_IS_CUMULATIVE: False
IMPORT_FROM_UNITS: kelvin
IMPORT_TO_UNITS: degC

IMPORT_START_DATE: 2025-01

DOWNLOAD_FOLDER: /app/data
DOWNLOAD_PREFIX: era5_hourly_temperature
TEMPORAL_AGGREGATION: mean